src/Entity/Corte.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CorteRepository")
 */
class Corte
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $espesor;

    /**
     * @ORM\Column(type="integer")
     */
    private $vel_corte;

    /**
     * @ORM\Column(type="integer")
     */
    private $t_pinchazo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEspesor(): ?float
    {
        return $this->espesor;
    }

    public function setEspesor(float $espesor): self
    {
        $this->espesor = $espesor;

        return $this;
    }

    public function getVelCorte(): ?int
    {
        return $this->vel_corte;
    }

    public function setVelCorte(int $vel_corte): self
    {
        $this->vel_corte = $vel_corte;

        return $this;
    }

    public function getTPinchazo(): ?int
    {
        return $this->t_pinchazo;
    }

    public function setTPinchazo(int $t_pinchazo): self
    {
        $this->t_pinchazo = $t_pinchazo;

        return $this;
    }
}

src/Form/CorteType.php
<?php

namespace App\Form;

use App\Entity\Corte;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CorteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('espesor', NumberType::class, array(
                'label' => 'Espesor',
                'attr' => array('class' => 'form-control')
            ))
            ->add('vel_corte', IntegerType::class, array(
                'label' => 'Velocidad corte',
                'attr' => array('class' => 'form-control')))
            ->add('t_pinchazo', IntegerType::class, array(
                'label' => 'Tiempo pinchazo',
                'attr' => array('class' => 'form-control')));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Corte::class,
        ]);
    }
}

src/Controller/CorteController.php
<?php

namespace App\Controller;

use App\Entity\Corte;
use App\Form\CorteType;
use App\Repository\CorteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/corte")
 */
class CorteController extends AbstractController
{
    /**
     * @Route("/", name="corte_index", methods="GET")
     */
    public function index(CorteRepository $corteRepository): Response
    {
        return $this->render('corte/index.html.twig', ['cortes' => $corteRepository->findAll()]);
    }

    /**
     * @Route("/new", name="corte_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $corte = new Corte();
        $form = $this->createForm(CorteType::class, $corte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($corte);
            $em->flush();

            return $this->redirectToRoute('corte_index');
        }

        return $this->render('corte/new.html.twig', [
            'corte' => $corte,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="corte_show", methods="GET")
     */
    public function show(Corte $corte): Response
    {
        return $this->render('corte/show.html.twig', ['corte' => $corte]);
    }

    /**
     * @Route("/{id}/edit", name="corte_edit", methods="GET|POST")
     */
    public function edit(Request $request, Corte $corte): Response
    {
        $form = $this->createForm(CorteType::class, $corte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('corte_edit', ['id' => $corte->getId()]);
        }

        return $this->render('corte/edit.html.twig', [
            'corte' => $corte,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="corte_delete", methods="DELETE")
     */
    public function delete(Request $request, Corte $corte): Response
    {
        if ($this->isCsrfTokenValid('delete'.$corte->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($corte);
            $em->flush();
        }

        return $this->redirectToRoute('corte_index');
    }
}

templates/corte/_delete_form.html.twig
<form method="post" action="{{ path('corte_delete', {'id': corte.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ corte.id) }}">
    <button class="btn">Delete</button>
</form>

templates/corte/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/corte/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Corte{% endblock %}

{% block body %}
    <h1>Edit Corte</h1>

    {{ include('corte/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('corte_index') }}">back to list</a>

    {{ include('corte/_delete_form.html.twig') }}
{% endblock %}

templates/corte/index.html.twig
{% extends 'layouts/dashboard.html.twig' %}

 {% block title %}Corte{% endblock %}
 {% block left_sidebar %}
     {{ include('partials/left_sidebar_acero.html.twig') }}
 {% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Espesor <br> (mm)</th>
                        <th>Velocidad Corte <br>(mm|min)</th>
                        <th>Tiempo Pinchazo <br>(seg)</th>
                        <th>actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for corte in cortes %}
                        <tr>
                            <td class="text-center">{{ corte.espesor }}</td>
                            <td>{{ corte.velCorte }}</td>
                            <td>{{ corte.tPinchazo }}</td>
                            <td>
                                <a href="{{ path('corte_show', {'id': corte.id}) }}">show</a>
                                <a href="{{ path('corte_edit', {'id': corte.id}) }}">edit</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <a href="{{ path('corte_new') }}">Agregar nuevo</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/corte/new.html.twig
{% extends 'layouts/dashboard.html.twig' %}

 {% block title %}Corte{% endblock %}
 {% block left_sidebar %}
     {{ include('partials/left_sidebar_acero.html.twig') }}
 {% endblock %}

{% block body %}
    <h1>Nuevo Corte</h1>

    {{ include('corte/_form.html.twig') }}

    <a href="{{ path('corte_index') }}">Regresar a la lista</a>
{% endblock %}

templates/corte/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Corte{% endblock %}

{% block body %}
    <h1>Corte</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ corte.id }}</td>
            </tr>
            <tr>
                <th>Espesor</th>
                <td>{{ corte.espesor }}</td>
            </tr>
            <tr>
                <th>Vel_corte</th>
                <td>{{ corte.velCorte }}</td>
            </tr>
            <tr>
                <th>T_pinchazo</th>
                <td>{{ corte.tPinchazo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('corte_index') }}">back to list</a>

    <a href="{{ path('corte_edit', {'id': corte.id}) }}">edit</a>

    {{ include('corte/_delete_form.html.twig') }}
{% endblock %}